# Generated by Django 2.2.4 on 2019-08-23 15:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('departure', models.DateField()),
                ('arrival', models.DateField()),
                ('type_of_flight', models.CharField(choices=[('OW', 'One-way'), ('RT', 'Round-trip'), ('DF', 'Direct-flight')], default='OW', max_length=2)),
                ('flight_status', models.CharField(choices=[('D', 'Delayed'), ('C', 'Cancelled'), ('E', 'En-route'), ('S', 'Scheduled'), ('L', 'Landed'), ('R', 'Redirected'), ('U', 'Unknown')], default='S', max_length=2)),
                ('flight_number', models.CharField(max_length=7)),
                ('airline', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('passengers', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('flight_number',),
            },
        ),
    ]
