# Generated by Django 2.2.4 on 2019-08-26 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('airtechapi', '0002_remove_flight_passengers'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='price',
            field=models.PositiveIntegerField(default=15000),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_tickets', models.PositiveSmallIntegerField(default=1)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airtechapi.Flight')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='flight',
            name='passengers',
            field=models.ManyToManyField(through='airtechapi.Booking', to=settings.AUTH_USER_MODEL),
        ),
    ]
