# Generated by Django 2.2.4 on 2019-08-26 11:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('airtechapi', '0003_auto_20190826_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
